# This file was generated by GoReleaser. DO NOT EDIT.
cask "skillet" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "48bdab6de2f668d101007831f6931544353e18ec6e27d817633df414d02e85f9"
      url "https://github.com/jegork/skillet/releases/download/v#{version}/skillet_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "467559eea56418b8516f14b64aaab565364180209e5211247c57ae2edaaa9c85"
      url "https://github.com/jegork/skillet/releases/download/v#{version}/skillet_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8ecce8d235c2c3998dbda35543b551770d78e9cb0f3d99164f6027611849eeca"
      url "https://github.com/jegork/skillet/releases/download/v#{version}/skillet_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cee2b32fa2b1ce09cfaff0cf74b7ae984f572cafbecfd93d1783e0946a4d2aca"
      url "https://github.com/jegork/skillet/releases/download/v#{version}/skillet_#{version}_linux_amd64.tar.gz"
    end
  end

  name "skillet"
  desc "Terminal UI for managing agent skills across Claude Code, Codex and omp"
  homepage "https://github.com/jegork/skillet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skillet"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/skillet"]
    end
  end

  # No zap stanza required
end
